### ISSUE TITLE
Driver selection incorrect when intel_pstates present. No way to override.

### ISSUE THREAD

**Issue by jiceathome** [Rongronggg9/power-profiles-daemon#2]
Linux can be so frustrating....
I'm running FC39 on a Lenovo X1 yoga Gen 8.
In standard configuration, the power is managed by the hardware with policy direction by the in-kernel intel_pstates driver.
The platform_profile module can't manage power in that configuration (If memory serves, I saw a msg to that effect in the log).

I found that power-profiles-daemon has a hard-coded list of drivers to use. It tries platform_profiles first and, because it's there (although incapable of managing power) it uses it. There's no way to override that choice. There's no way to remove the platform_profile module because the thinkpad_acpi modules depends on it (it'd better off without it in this case). There's no way to remove that dependency either. There's no way to remove the thinkpad_acpi module, it drives all the gadgets specific to my laptop. Note that I experimented removing both modules and that allows power-profiles-daemon to to its job flawlessly.

As a result the power management knob in the quick settings of gnome is perfectly ineffective.

I think it could be a simple mater to allow /var/lib/power-profiles-daemon/state.ini:Driver to override that choice. An even simpler fix might be to re-order to hard-coded list to place intel_pstate first.

**Comment by jiceatscion** [comment]
Ooops sorry. I re-filed the bug upstream.
