### ISSUE TITLE
conflicting information

### ISSUE THREAD

**Issue by Quephara** [Rongronggg9/power-profiles-daemon#5]
[the aur listing](https://aur.archlinux.org/packages/power-profiles-daemon-tlp-git) ahows the package to have a dependency on tlp. the driver cannot be installed on a system alongside TLP because there is a conflicting package

**Comment by Rongronggg9** [comment]
I do not maintain the AUR package. Please get in touch with the package maintainer to fix this.

**Comment by Rongronggg9** [comment]
It seems that it is [tlp](https://archlinux.org/packages/extra/any/tlp/) itself that conflicts with [power-profiles-daemon](https://archlinux.org/packages/extra/x86_64/power-profiles-daemon/). [power-profiles-daemon-tlp-git](https://aur.archlinux.org/packages/power-profiles-daemon-tlp-git) provides power-profiles-daemon, so it conflicts as well. Switching to [tlp-ppd-git](https://aur.archlinux.org/packages/tlp-ppd-git) should solve the issue.

Disclaimer: I am not an Arch Linux user. I infer this information from AUR and Arch Linux package index.

**Comment by Quephara** [comment]
thank you very much for this
